providers = ["python"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmds = [
  "python -m pip install --no-cache-dir -r requirements.txt",
  "python start_railway.py"
]
